### ISSUE TITLE
vdhcoapp: nodejs version issue

### ISSUE THREAD

**Issue by fabianhjr** [WolfangAukang/nur-packages#12]
```
error: Package ‘nodejs-12.22.12’ in /home/fabian/Development/Open/nixpkgs/main/pkgs/development/web/nodejs/v12.nix:11 is marked as insecure, refusing to evaluate.
```

On nixpkgs nodejs points to nodejs-12.x, attempting to bump to more recent versions.

**Comment by WolfangAukang** [comment]
What a coincidence, I am about to merge https://github.com/WolfangAukang/nur-packages/pull/11 which I created today. I am just cleaning up the repo, going to merge it soon.
